### ISSUE TITLE
Swift classes shouldn't subclass NSObject

### ISSUE THREAD

**Issue by edgarss** [blyscuit/Surveyer#4]
Unless using obj-c methods or KVO which isn't necessary for this code test

**Comment by blyscuit** [comment]
I admit this is my mistake in understanding Swift objects, thanks for the advice. I'll keep on learning about this pattern.

**Comment by blyscuit** [comment]
closed in https://github.com/blyscuit/Surveyer/commit/768c13fc848176880883872301e3493f5abf2d03
